### ISSUE TITLE
Script 4 object name error

### ISSUE THREAD

**Issue by jamiefaselt** [shannonspragg/SOI-Grizz#10]
`> crs(hm.dens.soi) == crs(soi.rast) # Nice, this worked --> now in BC Albers EPSG 3005
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'crs': object 'hm.dens.soi' not found`

line 63

**Comment by shannonspragg** [comment]
fixed with commit main 6753db1
